// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyBaiGiang_TaiNguyen.Data;

#nullable disable

namespace QuanLyBaiGiang_TaiNguyen.Migrations
{
    [DbContext(typeof(TaiNguyenDbContext))]
    [Migration("20230915013009_InitDB")]
    partial class InitDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QuanLyBaiGiang_TaiNguyen.Model.BaiGiang", b =>
                {
                    b.Property<string>("MaBG")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("KichThuoc")
                        .HasColumnType("float");

                    b.Property<string>("MaCD")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaMH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayGuiPD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TheLoai")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TinhTrangPD")
                        .HasColumnType("bit");

                    b.HasKey("MaBG");

                    b.HasIndex("MaCD");

                    b.ToTable("BaiGiangs");
                });

            modelBuilder.Entity("QuanLyBaiGiang_TaiNguyen.Model.ChuDe", b =>
                {
                    b.Property<string>("MaCD")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaMH")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenCD")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaCD");

                    b.ToTable("ChuDes");
                });

            modelBuilder.Entity("QuanLyBaiGiang_TaiNguyen.Model.TaiNguyen", b =>
                {
                    b.Property<string>("MaTN")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("KichThuoc")
                        .HasColumnType("float");

                    b.Property<string>("MaBG")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaCD")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaMH")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayGuiPD")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TheLoai")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TinhTrangPD")
                        .HasColumnType("bit");

                    b.HasKey("MaTN");

                    b.HasIndex("MaBG");

                    b.HasIndex("MaCD");

                    b.ToTable("TaiNguyens");
                });

            modelBuilder.Entity("QuanLyBaiGiang_TaiNguyen.Model.BaiGiang", b =>
                {
                    b.HasOne("QuanLyBaiGiang_TaiNguyen.Model.ChuDe", "ChuDe")
                        .WithMany()
                        .HasForeignKey("MaCD");

                    b.Navigation("ChuDe");
                });

            modelBuilder.Entity("QuanLyBaiGiang_TaiNguyen.Model.TaiNguyen", b =>
                {
                    b.HasOne("QuanLyBaiGiang_TaiNguyen.Model.BaiGiang", "BaiGiang")
                        .WithMany()
                        .HasForeignKey("MaBG");

                    b.HasOne("QuanLyBaiGiang_TaiNguyen.Model.ChuDe", "ChuDe")
                        .WithMany()
                        .HasForeignKey("MaCD");

                    b.Navigation("BaiGiang");

                    b.Navigation("ChuDe");
                });
#pragma warning restore 612, 618
        }
    }
}
