// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyVaiTro.Data;

#nullable disable

namespace QuanLyVaiTro.Migrations
{
    [DbContext(typeof(VaiTroDbContext))]
    [Migration("20230905035030_fixFK")]
    partial class fixFK
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QuanLyVaiTro.Model.PhanQuyen", b =>
                {
                    b.Property<string>("MaPQ")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaVT")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("PheDuyet")
                        .HasColumnType("bit");

                    b.Property<bool>("Sua")
                        .HasColumnType("bit");

                    b.Property<string>("TenChucNang")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ThemMoi")
                        .HasColumnType("bit");

                    b.Property<bool>("Xem")
                        .HasColumnType("bit");

                    b.Property<bool>("Xoa")
                        .HasColumnType("bit");

                    b.HasKey("MaPQ");

                    b.HasIndex("MaVT");

                    b.ToTable("PhanQuyen");
                });

            modelBuilder.Entity("QuanLyVaiTro.Model.VaiTro", b =>
                {
                    b.Property<string>("MaVT")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenVT")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaVT");

                    b.ToTable("VaiTro");
                });

            modelBuilder.Entity("QuanLyVaiTro.Model.PhanQuyen", b =>
                {
                    b.HasOne("QuanLyVaiTro.Model.VaiTro", "VaiTro")
                        .WithMany("PhanQuyens")
                        .HasForeignKey("MaVT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("QuanLyVaiTro.Model.VaiTro", b =>
                {
                    b.Navigation("PhanQuyens");
                });
#pragma warning restore 612, 618
        }
    }
}
