// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyThong_Bao.Data;

#nullable disable

namespace QuanLyThong_Bao.Migrations
{
    [DbContext(typeof(ThongBaoDbContext))]
    partial class ThongBaoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QuanLyThong_Bao.Model.GuiThongBao", b =>
                {
                    b.Property<int>("STT")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("STT"), 1L, 1);

                    b.Property<string>("MaNguoiGui")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaNguoiNhan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaTB")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("STT");

                    b.HasIndex("MaTB");

                    b.ToTable("GuiThongBao");
                });

            modelBuilder.Entity("QuanLyThong_Bao.Model.LoaiThongBao", b =>
                {
                    b.Property<string>("MaLTB")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenLTB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLTB");

                    b.ToTable("LoaiThongbao");
                });

            modelBuilder.Entity("QuanLyThong_Bao.Model.ThongBao", b =>
                {
                    b.Property<string>("MaTB")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaLTB")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTB");

                    b.HasIndex("MaLTB");

                    b.ToTable("ThongBao");
                });

            modelBuilder.Entity("QuanLyThong_Bao.Model.GuiThongBao", b =>
                {
                    b.HasOne("QuanLyThong_Bao.Model.ThongBao", "ThongBao")
                        .WithMany()
                        .HasForeignKey("MaTB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThongBao");
                });

            modelBuilder.Entity("QuanLyThong_Bao.Model.ThongBao", b =>
                {
                    b.HasOne("QuanLyThong_Bao.Model.LoaiThongBao", "LoaiThongBao")
                        .WithMany("ThongBaos")
                        .HasForeignKey("MaLTB")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiThongBao");
                });

            modelBuilder.Entity("QuanLyThong_Bao.Model.LoaiThongBao", b =>
                {
                    b.Navigation("ThongBaos");
                });
#pragma warning restore 612, 618
        }
    }
}
